name: tapsilat
description: Flutter SDK for Tapsilat, Create orders and retrieve secure checkout URLs
version: 0.3.3
homepage: https://github.com/tapsilat
repository: https://github.com/tapsilat/tapsilat-flutter
issue_tracker: https://github.com/tapsilat/tapsilat-flutter/issues
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.26.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.2.2
dev_dependencies:
  test: ^1.26.3
flutter:
  plugin:
    platforms:
      android:
        package: tapsilat
        pluginClass: TapsilatPlugin
      ios:
        pluginClass: TapsilatPlugin
      web:
        pluginClass: TapsilatPlugin
        fileName: tapsilat_web.dart
      macos:
        pluginClass: TapsilatPlugin
      linux:
        pluginClass: TapsilatPlugin
        fileName: tapsilat_plugin.cc
      windows:
        pluginClass: TapsilatPluginCApi
        fileName: tapsilat_plugin_c_api.cpp